# MySQL. Versions 5.5.8 and up are supported.

default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: payjp_practice_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: payjp_practice_test

production:
  <<: *default
  database: payjp_practice_production
  url: <%= ENV['DATABASE_URL'] %>
